export const APP = Object.freeze({
  name: "Gestão de Folgas",
  version: "6.2.9-firebase-github",
  profiles: {
    admin: "Administrador",
    manager: "Responsável de loja",
    kitchen: "Chefe de cozinha",
    employee: "Funcionário",
  },
  status: {
    pending: "Pendente",
    approved: "Aprovada",
    rejected: "Rejeitada",
    cancelled: "Cancelada",
    completed: "Concluída",
  },
});

const MANAGER_PERMISSIONS = [
  "dashboard.read",
  "stores.own.read",
  "employees.own.read",
  "timeoff.ownstore.read",
  "timeoff.ownstore.create",
  "timeoff.ownstore.update",
  "timeoff.ownstore.approve",
  "timeoff.ownstore.reject",
  "timeoff.ownstore.cancel",
  "scheduler.ownstore.run",
  "calendar.ownstore.read",
  "reports.ownstore.read",
  "operations.ownstore.manage",
  "swaps.ownstore.manage",
  "notifications.ownstore.read",
];

export const PERMISSIONS = Object.freeze({
  Administrador: ["*"],
  "Responsável de loja": MANAGER_PERMISSIONS,
  Gerente: MANAGER_PERMISSIONS,
  "Chefe de cozinha": [
    "dashboard.read",
    "stores.own.read",
    "employees.own.read",
    "timeoff.ownstore.read",
    "calendar.ownstore.read",
    "timeclock.ownstore.read",
    "notifications.ownstore.read",
  ],
  Funcionário: [
    "dashboard.self.read",
    "timeoff.self.read",
    "timeoff.self.request",
    "timeoff.self.cancel_pending",
    "calendar.ownstore.private.read",
    "swaps.self.request",
    "swaps.self.respond",
    "timeoff.self.acknowledge",
    "notifications.self.read",
  ],
});

export const ID_FIELDS = Object.freeze({
  Configuracoes: "Chave",
  Lojas: "LojaID",
  Funcionarios: "FuncionarioID",
  Folgas: "FolgaID",
  Feriados: "FeriadoID",
  RegrasFolga: "RegraID",
  MovimentosSaldoFolgas: "MovimentoID",
  Auditoria: "AuditoriaID",
  Notificacoes: "NotificacaoID",
  RegrasOperacionais: "RegraOperacionalID",
  CienciasFolga: "CienciaID",
  TrocasFolga: "TrocaID",
  DiretorioTrocasFolga: "FuncionarioID",
  ArenaRanking: "RankingID",
  RegistrosPonto: "RegistroPontoID",
  AjustesPonto: "AjustePontoID",
  JustificativasPonto: "JustificativaPontoID",
  JornadasPonto: "JornadaPontoID",
  LocaisPonto: "LocalPontoID",
  BancoHoras: "BancoHorasID",
  Ferias: "FeriasID",
  Documentos: "DocID",
  Onboarding: "OnbID",
  Comunicados: "ComID",
  ComunicadosLeituras: "LeituraID",
  Enquetes: "EnqID",
  EnquetesVotos: "VotoID",
  Delegacoes: "DelID",
  Substituicoes: "SubID",
  FechamentosMensais: "FechamentoID",
  FolhaLinhas: "LinhaID",
  BancoHorasMovimentos: "MovID",
});

export const PUBLIC_AUTH_TABLES = new Set([
  "Configuracoes",
  "Feriados",
  "RegrasFolga",
  "ArenaRanking",
]);

export const STORE_SCOPED_FIELDS = Object.freeze({
  Lojas: "LojaID",
  Funcionarios: "LojaID",
  Folgas: "LojaID",
  RegrasOperacionais: "LojaID",
  TrocasFolga: "LojaID",
  DiretorioTrocasFolga: "LojaID",
  RegistrosPonto: "LojaID",
  AjustesPonto: "LojaID",
  JustificativasPonto: "LojaID",
  JornadasPonto: "LojaID",
  LocaisPonto: "LojaID",
  BancoHoras: "LojaID",
  Ferias: "LojaID",
  Documentos: "LojaID",
  Onboarding: "LojaID",
  Comunicados: "LojaID",
  ComunicadosLeituras: "LojaID",
  Enquetes: "LojaID",
  EnquetesVotos: "LojaID",
  Substituicoes: "LojaID",
  FechamentosMensais: "LojaID",
  FolhaLinhas: "LojaID",
  BancoHorasMovimentos: "LojaID",
  Notificacoes: "LojaID",
  Delegacoes: "LojaID",
});

export const EMPLOYEE_SCOPED_FIELDS = Object.freeze({
  Funcionarios: "FuncionarioID",
  Folgas: "FuncionarioID",
  CienciasFolga: "FuncionarioID",
  TrocasFolga: "FuncionarioID",
  RegistrosPonto: "FuncionarioID",
  AjustesPonto: "FuncionarioID",
  JustificativasPonto: "FuncionarioID",
  JornadasPonto: "FuncionarioID",
  BancoHoras: "FuncionarioID",
  Ferias: "FuncionarioID",
  Documentos: "FuncionarioID",
  Onboarding: "FuncionarioID",
  ComunicadosLeituras: "FuncionarioID",
  EnquetesVotos: "FuncionarioID",
  Substituicoes: "FuncionarioOrigem",
  BancoHorasMovimentos: "FuncionarioID",
  Notificacoes: "DestinatarioID",
});

export const DEFAULT_CONFIG = [
  {
    Chave: "Nome da empresa",
    Valor: "Minha Empresa",
    Descricao: "Nome apresentado na aplicação",
  },
  {
    Chave: "Limite padrão de funcionários de folga por dia",
    Valor: "1",
    Descricao: "Limite diário padrão",
  },
  {
    Chave: "Permitir pedidos aos fins de semana",
    Valor: "true",
    Descricao: "Aceita pedidos no sábado e domingo",
  },
  {
    Chave: "Exigir aprovação",
    Valor: "true",
    Descricao: "Pedidos de funcionários ficam pendentes",
  },
  {
    Chave: "Prazo mínimo de antecedência",
    Valor: "3",
    Descricao: "Dias mínimos antes da folga",
  },
  {
    Chave: "Prazo máximo para pedido",
    Valor: "180",
    Descricao: "Dias máximos no futuro",
  },
  {
    Chave: "Permitir meia folga",
    Valor: "true",
    Descricao: "Permite manhã ou tarde",
  },
  {
    Chave: "Permitir folga em feriado",
    Valor: "true",
    Descricao: "Permite folga em feriado",
  },
  {
    Chave: "País ou região",
    Valor: "BR",
    Descricao: "Código do país",
  },
  {
    Chave: "Fuso horário",
    Valor: "America/Fortaleza",
    Descricao: "Fuso usado pelo sistema",
  },
];

export const ARENA_GAMES = Object.freeze({
  corrida_pedidos: { name: "Rush de Pedidos", durationMs: 45000 },
  bandeja_perfeita: { name: "Bandeja Neon", durationMs: 45000 },
  caixa_turbo: { name: "Caixa Turbo", durationMs: 45000 },
  molho_no_ponto: { name: "Molho no Ponto 2", durationMs: 45000 },
  monte_lanche: { name: "Burger Stack", durationMs: 45000 },
  caca_erro: { name: "Intruso na Chapa", durationMs: 45000 },
  delivery_relampago: { name: "Delivery Relâmpago", durationMs: 45000 },
  cozinha_panico: { name: "Cozinha em Pânico", durationMs: 45000 },
  pega_ladrao_batata: { name: "Operação Batata", durationMs: 45000 },
  rota_motoboy: { name: "Central de Rotas", durationMs: 45000 },
  garcom_equilibrista: { name: "Bandeja em Jogo", durationMs: 45000 },
  house_link: { name: "House Link", durationMs: 90000 },
});

export const ARENA_PRODUCTS = [
  { id: "burger", nome: "Burger", emoji: "🍔", cor: "#ef4444" },
  { id: "frango_crocante", nome: "Frango crocante", emoji: "🍗", cor: "#f97316" },
  { id: "batata", nome: "Batata frita", emoji: "🍟", cor: "#eab308" },
  { id: "milkshake", nome: "Milk-shake", emoji: "🥤", cor: "#ec4899" },
  { id: "hot_dog", nome: "Hot dog", emoji: "🌭", cor: "#dc2626" },
  { id: "onion_rings", nome: "Onion rings", emoji: "🧅", cor: "#a855f7" },
  { id: "combo", nome: "Combo da casa", emoji: "🍱", cor: "#8b5cf6" },
  { id: "refrigerante", nome: "Refrigerante", emoji: "🧊", cor: "#06b6d4" },
  { id: "sobremesa", nome: "Sobremesa", emoji: "🍨", cor: "#f472b6" },
  { id: "molho", nome: "Molho especial", emoji: "🌶️", cor: "#e11d48" },
  { id: "salada", nome: "Salada", emoji: "🥗", cor: "#22c55e" },
];

export const ARENA_INGREDIENTS = [
  { id: "pao_base", nome: "Pão de baixo", emoji: "🟤" },
  { id: "carne", nome: "Carne", emoji: "🥩" },
  { id: "queijo", nome: "Queijo", emoji: "🧀" },
  { id: "alface", nome: "Alface", emoji: "🥬" },
  { id: "tomate", nome: "Tomate", emoji: "🍅" },
  { id: "cebola", nome: "Cebola", emoji: "🧅" },
  { id: "molho", nome: "Molho", emoji: "🌶️" },
  { id: "bacon", nome: "Bacon", emoji: "🥓" },
  { id: "pao_topo", nome: "Pão de cima", emoji: "🟠" },
];
