import {scheduleForDay, workday, active, shiftDate} from "./core/reminder-policy.js";
// Presentation only: all clock mutations stay in the existing validated flow.
const $ = (s) => document.querySelector(s);
const list = (x) => Array.isArray(x) ? x : [];
const esc = (x) => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time = (d = new Date()) => new Date(d).toLocaleTimeString('pt-BR',{timeZone:'America/Bahia',hour:'2-digit',minute:'2-digit'});
const dateKey = (d = new Date()) => new Intl.DateTimeFormat('en-CA',{timeZone:'America/Bahia',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const hours = n => `${Math.floor(Math.max(0,n)/60)}h${String(Math.round(Math.max(0,n)%60)).padStart(2,'0')}`;
let data = {}, unit = '', teamFilter = 'todos', search = '', mode = 'dia';
const names = {trabalhando:'Trabalhando',intervalo:'Em intervalo',ausente:'Sem entrada',folga:'Folga',concluido:'Encerrado'};
const colors = {trabalhando:'#71cbb0',intervalo:'#ecd47c',ausente:'#eea69e',folga:'#c7b4eb',concluido:'#9bbce5'};
function rows() { return data.manager ? list(data.presence?.presence).filter(p => !unit || String(p.LojaID) === unit) : []; }
function delay(p) {
 const expected=String(p.horarioEscala || '').match(/(\d{2}):(\d{2})/), actual=String(p.entryTime || '').match(/^(\d{2}):(\d{2})/);
 if(!expected || !actual) return 0;
 const difference=(Number(actual[1])*60+Number(actual[2]))-(Number(expected[1])*60+Number(expected[2]));
 return Math.max(0, difference>720?difference-1440:difference < -720?difference+1440:difference);
}
function avatar(p) { return `<span class="j-avatar" style="--avatar:${colors[p.status] || '#c7b4eb'}">${esc((p.Nome || '?').split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join(''))}</span>`; }
function person(p) { return `<article class="j-person">${avatar(p)}<div><strong>${esc(p.Nome)}</strong><small>${esc(p.Cargo)} · ${esc(p.NomeLoja || 'Unidade')}</small><span>${p.status === 'intervalo' ? 'Intervalo desde '+esc(p.lastPunchTime || '—') : p.entryTime ? 'Entrada '+esc(p.entryTime)+' · '+esc(p.elapsedTexto || '') : esc(p.statusLabel)}</span></div><span class="j-status" style="--status:${colors[p.status]}">${esc(names[p.status] || p.statusLabel)}</span></article>`; }
function clock() { return `<article class="j-card j-clock"><div class="j-card-top"><span>SEU TEMPO IMPORTA</span><span class="j-live"><i></i> AO VIVO</span></div><time class="j-digital" data-live-clock>--:--:--</time><div class="j-date" data-live-date></div><div class="j-clock-bottom"><span>Hoje é um bom dia para fazer acontecer.</span><button class="btn btn-primary" data-view-target="timeclock">Bater ponto ↗</button></div></article>`; }
function unitSelect() { return data.manager ? `<label class="j-unit">Unidade <select data-j-unit><option value="">Todas as unidades</option>${list(data.stores).map(s=>`<option value="${esc(s.LojaID)}" ${String(s.LojaID)===unit?'selected':''}>${esc(s.Nome)}</option>`).join('')}</select></label>` : ''; }
function operation() {
 const r=rows(), present=r.filter(p=>['trabalhando','intervalo'].includes(p.status)).length;
 const pct=r.length?Math.round(present/r.length*100):0;
 let pos=0; const gradient=Object.entries(colors).map(([k,c])=>{const start=pos;pos+=r.filter(p=>p.status===k).length/Math.max(1,r.length)*100;return `${c} ${start}% ${pos}%`}).join(',');
 const counts=['trabalhando','intervalo','atrasos','ausente'].map(k=>`<article class="j-stat" style="--tint:${colors[k] || '#eea69e'}33"><span class="j-stat-icon" style="color:${colors[k]}">●</span><strong>${data.presence?(k==='atrasos'?r.filter(p=>delay(p)>0).length:r.filter(p=>p.status===k).length):'—'}</strong><span>${k==='atrasos'?'Entradas após o horário':names[k]}</span></article>`).join('');
 const recent=r.filter(p=>p.lastPunchTime).sort((a,b)=>b.lastPunchTime.localeCompare(a.lastPunchTime)).slice(0,5);
 const alerts=r.filter(p=>p.alertMessage || delay(p)>0).sort((a,b)=>(b.alertLevel==='danger')-(a.alertLevel==='danger'));
 return `<div class="j-stats">${counts}</div><article class="j-card j-team-chart"><div class="j-card-top"><h3>Equipe agora</h3><span class="j-live"><i></i> AO VIVO</span></div><div class="j-donut-wrap"><div class="j-donut" role="img" aria-label="${pct}% da equipe presente" style="background:conic-gradient(${r.length?gradient:'#eceaf2 0% 100%'})"><div><strong>${data.presence?pct+'%':'—'}</strong><small>Presentes</small></div></div><div class="j-legend">${Object.entries(names).map(([k,n])=>`<span><i style="background:${colors[k]}"></i>${n}<b>${r.filter(p=>p.status===k).length}</b></span>`).join('')}</div></div><small>Presentes = trabalhando + intervalo. Sem entrada não confirma falta.</small></article><article class="j-card j-people"><div class="j-card-top"><div><h3>Agora na empresa</h3><small>${present} de ${r.length} colaboradores presentes</small></div><div class="j-avatar-stack">${r.filter(p=>['trabalhando','intervalo'].includes(p.status)).slice(0,4).map(avatar).join('')}</div></div>${r.slice(0,3).map(person).join('') || '<p class="j-empty">Aguardando os dados da equipe.</p>'}<button class="btn btn-ghost" data-view-target="live-team">Ver toda a equipe →</button></article><article class="j-card"><div class="j-card-top"><h3>Atividade ao vivo</h3><span class="j-live"><i></i></span></div><p class="j-caption">Última marcação de cada pessoa</p><div class="j-activity">${recent.map(p=>`<div><time>${esc(p.lastPunchTime)}</time><i></i><span><strong>${esc(p.Nome)}</strong><small>${esc({ENTRADA:'registrou entrada',SAIDA_INTERVALO:'iniciou intervalo',RETORNO_INTERVALO:'voltou do intervalo',SAIDA_FINAL:'encerrou a jornada'}[p.lastPunchType] || p.statusLabel)}</small></span></div>`).join('') || '<p class="j-empty">Nenhuma marcação disponível.</p>'}</div></article><article class="j-card j-attention"><h3>Precisa da sua atenção</h3>${alerts.slice(0,3).map(p=>`<p><strong>${esc(p.Nome)}</strong><br>${esc(p.alertMessage || `${delay(p)} min após o horário previsto`)}</p>`).join('') || '<p>Nenhum alerta de jornada nesta seleção.</p>'}<button class="btn btn-secondary" data-view-target="pending-center">Revisar solicitações →</button></article><article class="j-card j-insight"><span class="eyebrow">✦ INSIGHTS</span><h3>${data.presence?`${present} pessoas presentes agora`:'Sua operação em um só lugar'}</h3><p>${r.filter(p=>p.status==='intervalo').length} em intervalo. ${r.filter(p=>p.status==='ausente').length} sem entrada registrada.</p><button class="btn btn-ghost" data-view-target="timeclock">Ver jornada →</button></article>`;
}
function personal() {
 const d=data.clock, days=list(d?.days), today=days.find(x=>x.data===(d?.date || dateKey())) || (d?._quick?d.summary:null), marks=list(d?.todayRecords);
 const labels={ENTRADA:'Entrada',SAIDA_INTERVALO:'Intervalo',RETORNO_INTERVALO:'Retorno',SAIDA_FINAL:'Saída'};
 const monday=new Date(dateKey()+'T12:00:00-03:00');monday.setDate(monday.getDate()-(monday.getDay()+6)%7);
 const week=Array.from({length:7},(_,i)=>{const day=new Date(monday);day.setDate(day.getDate()+i);return {label:['SEG','TER','QUA','QUI','SEX','SÁB','DOM'][i],value:days.find(x=>x.data===dateKey(day))};});
 const total=week.reduce((n,x)=>n+Number(x.value?.trabalhadoMinutos||0),0),max=Math.max(480,...week.map(x=>Number(x.value?.trabalhadoMinutos||0)));
 return `<article class="j-card j-journey"><div class="j-card-top"><h3>Jornada de hoje</h3><span class="j-status">${!d?'Carregando…':d.offToday?'De folga':({SAIDA_INTERVALO:'Trabalhando',RETORNO_INTERVALO:'Em intervalo',SAIDA_FINAL:'Trabalhando',ENTRADA:'Aguardando entrada'}[d.nextAction] || 'Jornada encerrada')}</span></div><div class="j-journey-line">${['ENTRADA','SAIDA_INTERVALO','RETORNO_INTERVALO','SAIDA_FINAL'].map(k=>{const m=marks.find(x=>x.TipoMarcacao===k);return `<div class="${m?'done':''}"><i></i><strong>${m?esc(time(m.DataHora)):'—'}</strong><small>${labels[k]}</small></div>`;}).join('')}</div><div class="j-totals"><span>Previsto<b>${esc(today?.previstoTexto || '—')}</b></span><span>Realizado<b>${esc(today?.trabalhadoTexto || '—')}</b></span><span>Restante<b>${today?hours(Math.max(0,today.previstoMinutos-today.trabalhadoMinutos)):'—'}</b></span></div><button class="btn btn-primary j-wide" data-view-target="timeclock">${({ENTRADA:'Registrar entrada',SAIDA_INTERVALO:'Iniciar intervalo',RETORNO_INTERVALO:'Finalizar intervalo',SAIDA_FINAL:'Registrar saída'}[d?.nextAction] || 'Abrir meu ponto')}</button></article><article class="j-card j-week"><div class="j-card-top"><h3>Minha semana</h3><button class="btn btn-ghost" data-view-target="timeclock">Ver detalhes →</button></div><div class="j-bars">${week.map(x=>`<div><small>${x.value?hours(x.value.trabalhadoMinutos):'—'}</small><div><i style="height:${x.value?Math.max(2,x.value.trabalhadoMinutos/max*100):0}%"></i></div><span>${x.label}</span></div>`).join('')}</div><div class="j-totals"><span>Total registrado<b>${days.length?hours(total):'—'}</b></span><span>Banco de horas<b>${esc(data.balance?.totalTexto || '—')}</b></span></div>${!days.length?'<p class="j-caption">Abra o ponto para carregar o histórico da semana.</p>':''}</article>`;
}
function renderTeam() {
 const r=rows().filter(p=>(teamFilter==='todos'||(teamFilter==='atrasados'?delay(p)>0:p.status===teamFilter))&&`${p.Nome} ${p.Cargo} ${p.NomeLoja}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
 $('#journeyTeam').innerHTML=data.manager?`<div class="j-page-head"><div><span class="eyebrow">PESSOAS QUE FAZEM ACONTECER</span><h2>Equipe</h2><p>${rows().length} colaboradores</p></div>${unitSelect()}</div><label class="j-search">Buscar colaborador<input data-j-search type="search" placeholder="Nome, cargo ou unidade…" value="${esc(search)}"></label><div class="j-chips">${[['todos','Todos'],['atrasados','Atrasados'],...Object.entries(names)].map(([k,n])=>`<button data-j-filter="${k}" aria-pressed="${teamFilter===k}">${n}</button>`).join('')}</div><div id="journeyTeamRows" class="j-team-list">${r.map(person).join('')||'<p class="j-empty">Nenhuma pessoa nesta seleção.</p>'}</div>`:'<p class="j-empty">A visualização da equipe está disponível para gestores.</p>';
}
function renderSchedule() {
 const today=dateKey(), start=mode==='mês'?today.slice(0,7)+'-01':mode==='semana'?shiftDate(today,-((new Date(today+'T12:00:00Z').getUTCDay()+6)%7)):today;
 const count=mode==='mês'?new Date(Number(today.slice(0,4)),Number(today.slice(5,7)),0).getDate():mode==='semana'?7:1;
 const own=String(data.user?.funcionarioId || data.user?.FuncionarioID || '');
 const employees=list(data.employees).filter(p=>active(p.Ativo)&&(!unit||String(p.LojaID)===unit)&&(data.manager||String(p.FuncionarioID)===own));
 const blocks=Array.from({length:count},(_,i)=>{const day=shiftDate(start,i);const shifts=employees.map(p=>({p,s:scheduleForDay(list(data.schedules),p.FuncionarioID,day)})).filter(({p,s})=>s&&workday(p,s,day,list(data.timeOff))).sort((a,b)=>String(a.s.HoraEntrada).localeCompare(String(b.s.HoraEntrada)));
 return `<article class="j-card ${day===today?'j-is-today':''}"><span class="eyebrow">${day===today?'HOJE · ':''}${new Date(day+'T12:00:00Z').toLocaleDateString('pt-BR',{timeZone:'America/Bahia',weekday:'short',day:'2-digit',month:'short'})}</span>${shifts.map(({p,s})=>`<div class="j-shift"><time>${esc(s.HoraEntrada || '—')} — ${esc(s.HoraSaida || '—')}</time>${avatar(p)}<div><strong>${esc(p.Nome)}</strong><small>${esc(p.NomeLoja || 'Jornada prevista')}</small></div></div>`).join('')||'<p class="j-empty">Sem jornada prevista nesta seleção.</p>'}</article>`;}).join('');
 $('#journeySchedule').innerHTML=`<div class="j-page-head"><div><span class="eyebrow">SEU PRÓXIMO PASSO</span><h2>Escala</h2><p>Jornadas cadastradas e folgas aprovadas</p></div>${unitSelect()}</div><div class="j-chips">${['dia','semana','mês'].map(k=>`<button data-j-mode="${k}" aria-pressed="${mode===k}">${k}</button>`).join('')}</div><div class="j-schedule-grid">${data.schedules?blocks:'<p class="j-empty">Carregando jornadas…</p>'}</div><button class="btn btn-secondary" data-view-target="calendar">Consultar e gerenciar folgas →</button>`;
}

function render() {
 if(!$('#journeyHome'))return;
 $('#journeyHome').innerHTML=`<div class="j-toolbar">${unitSelect()}<span>O seu dia, em tempo real</span></div>${clock()}${data.manager?operation():personal()}`;
 $('#view-dashboard').classList.toggle('j-unit-filtered',!!unit);
 renderTeam();renderSchedule();tick();
}
function tick(){const now=new Date();document.querySelectorAll('[data-live-clock]').forEach(e=>e.textContent=now.toLocaleTimeString('pt-BR',{timeZone:'America/Bahia',hour:'2-digit',minute:'2-digit',second:'2-digit'}));document.querySelectorAll('[data-live-date]').forEach(e=>e.textContent=now.toLocaleDateString('pt-BR',{timeZone:'America/Bahia',weekday:'long',day:'2-digit',month:'short',year:'numeric'}));}
window.addEventListener('house-journey',e=>{data=e.detail || {};render()});
document.addEventListener('change',e=>{if(e.target.matches('[data-j-unit]')){unit=e.target.value;render();}});
document.addEventListener('input',e=>{if(e.target.matches('[data-j-search]')){search=e.target.value;const r=rows().filter(p=>(teamFilter==='todos'||(teamFilter==='atrasados'?delay(p)>0:p.status===teamFilter))&&`${p.Nome} ${p.Cargo} ${p.NomeLoja}`.toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));$('#journeyTeamRows').innerHTML=r.map(person).join('')||'<p class="j-empty">Nenhuma pessoa nesta seleção.</p>';}});
document.addEventListener('click',e=>{const f=e.target.closest('[data-j-filter]'),m=e.target.closest('[data-j-mode]');if(f){teamFilter=f.dataset.jFilter;renderTeam();}if(m){mode=m.dataset.jMode;renderSchedule();}});
setInterval(()=>{if(!document.hidden)tick();},1000);
